### ISSUE TITLE
GKE Nginx Value Issue

### ISSUE THREAD

**Issue by otavioss** [boldbi/boldbi-kubernetes#123]
The ingress generated by GKE recommended values does not work, and that server-snippet is too complex and causes a lot of intermittent 404:

https://github.com/boldbi/boldbi-kubernetes/blob/26c49209f408bc7557ffee92f16dd92ccb7b38b7/helm/boldbi/templates/ingress.yaml#L32-L40

The helm template does not allow changing the ingress class: 
https://github.com/boldbi/boldbi-kubernetes/blob/7539a7a3b86c52e3bb14e1fdcb1edd368931f92b/helm/bold-common/templates/ingress.yaml#L16

https://github.com/boldbi/boldbi-kubernetes/blob/26c49209f408bc7557ffee92f16dd92ccb7b38b7/helm/boldbi/templates/ingress.yaml#L510-L512

Here is a sample of a ingress that works
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bold-ingress-
  namespace: bold-bi
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: "bold.k8s.pod.id"
    nginx.ingress.kubernetes.io/session-cookie-max-age: '600'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "16k"
    nginx.ingress.kubernetes.io/fastcgi-buffers: "16k"
    nginx.ingress.kubernetes.io/fastcgi-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: example
  tls:
  - hosts:
    - bold-bi.example.com
    - www.bold-bi.example.com
    secretName: bold-bi-tls
  rules:
  - host: bold-bi.example.com
    http:
      paths:
      - path: "/bi/api/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-api-service
            port:
              number: 6005
      - path: "/bi/jobs/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-jobs-service
            port:
              number: 6006
      - path: "/bi/designer/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-dataservice-service
            port:
              number: 6007
      - path: "/bi/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-web-service
            port:
              number: 6004
      - path: "/api/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: id-api-service
            port:
              number: 6001
      - path: "/ums/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: id-ums-service
            port:
              number: 6002
      - path: "/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: id-web-service
            port:
              number: 6000
 ```
 
The ETL service needs to be created separately due to the rewrite target, if added together the application will return 502:
 
 ```
 apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bold-ingress-etl
  namespace: bold-bi
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: "bold.k8s.pod.id"
    nginx.ingress.kubernetes.io/session-cookie-max-age: '600'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "16k"
    nginx.ingress.kubernetes.io/fastcgi-buffers: "16k"
    nginx.ingress.kubernetes.io/fastcgi-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: example
  tls:
  - hosts:
    - bold-bi.example.com
    - www.bold-bi.example.com
    secretName: bold-bi-tls
  rules:
  - host: bold-bi.example.com
    http:
      paths:
      - path: "/etlservice(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bold-etl-service
            port:
              number: 6009
 ```
