### ISSUE TITLE
Improvement Request: Add Tolerations and Affinity to the helm template 

### ISSUE THREAD

**Issue by otavioss** [boldbi/boldbi-kubernetes#124]
The inclusion of the tolerations field in the helm template is necessary due to the substantial resource requirements for autoscaling Bold Bi. 
To ensure high availability, we should consider implementing pod affinity and anti-affinity to control the placement of pods.

Example:

```
      tolerations:
        {{- range .Values.tolerations }}
        - key: "{{ .key }}"
          operator: "{{ .operator }}"
          value: "{{ .value }}"
          effect: "{{ .effect }}"
          tolerationSeconds: {{ .tolerationSeconds | default "0" }}
             affinity:
        podAffinity:
          {{- with .Values.podAffinity }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
        podAntiAffinity:
          {{- with .Values.podAntiAffinity }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
```

Values file:

```
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
    tolerationSeconds: 3600
  - key: "example.com/some-key"
    operator: "Equal"
    value: "some-value"
    effect: "NoExecute"
    tolerationSeconds: 1800
    
podAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: "app"
            operator: In
            values:
              - {{ .Chart.Name }}
      topologyKey: "kubernetes.io/hostname"

podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: "app"
            operator: In
            values:
              - {{ .Chart.Name }}
      topologyKey: "kubernetes.io/hostname"
```
