### ISSUE TITLE
Missing a way to use existing secrets for DB and License

### ISSUE THREAD

**Issue by am-tribia** [boldbi/boldbi-kubernetes#131]
In our k8 cluster setup, we use Secret Vaults to distribute sensitive information like DB passwords and license keys. The current helm chart implementation doesn't support using an existing secret that mandates us to provide the DB password and License key as plain text in values.yml.

I would suggest implementing something like below to use existing secret

```
{{- if not .Values.licenseKeyDetails.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:  
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-license-key
{{ include "boldbi.namespace" . | indent 2 }}
type: Opaque
stringData:
  BOLD_SERVICES_UNLOCK_KEY: "{{ .Values.licenseKeyDetails.licenseKey }}"
{{- end }}



{{- if not .Values.databaseServerDetails.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:  
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-db-secret
{{ include "boldbi.namespace" . | indent 2 }}
type: Opaque
stringData:
  BOLD_SERVICES_DB_TYPE: "{{ .Values.databaseServerDetails.dbType }}"
  BOLD_SERVICES_DB_HOST: "{{ .Values.databaseServerDetails.dbHost }}"
  BOLD_SERVICES_DB_PORT: "{{ .Values.databaseServerDetails.dbPort }}"
  BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB: "{{ .Values.databaseServerDetails.maintenanceDB }}"
  BOLD_SERVICES_DB_USER: "{{ .Values.databaseServerDetails.dbUser }}"
  BOLD_SERVICES_DB_PASSWORD: "{{ .Values.databaseServerDetails.dbPassword }}"
  BOLD_SERVICES_DB_ADDITIONAL_PARAMETERS: "{{ .Values.databaseServerDetails.dbAdditionalParameters }}"
  BOLD_SERVICES_DB_NAME: "{{ .Values.databaseServerDetails.dbName }}"
{{- end }}
```
